apiVersion: v1
kind: ConfigMap
metadata:
  name: shortener-config
  namespace: shortener
data:
  APP_ENV: "production"
  PORT: "3000"
  DB_HOST: "postgres-svc"
  DB_PORT: "5432"
  DB_NAME: "shortenerdb"

